plugins {
    id 'java'
    id 'jacoco'
}

group = 'org.programs'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    implementation 'com.google.guava:guava:33.5.0-jre'
    implementation 'org.json:json:20250517'
    testImplementation 'org.testng:testng:7.11.0'
}

test {
    useTestNG {
        suites 'src/test/resources/testng.xml'
    }

    testLogging {
        events "passed", "failed", "skipped"
        showStandardStreams = true
        exceptionFormat = 'full'
    }

    // Automatically generate JaCoCo report after tests
    finalizedBy jacocoTestReport
}

jacoco {
    toolVersion = "0.8.13"
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = true
        csv.required = false
    }
}

/*
 * Comment this block later when your project has enough test coverage.
 * This will fail the build if coverage drops below 10%.
 */
jacocoTestCoverageVerification {
    violationRules {
        rule {
            enabled = true
            limit {
                minimum = 0.10
            }
        }
    }
}

check.dependsOn jacocoTestCoverageVerification
*/

jar {
    manifest {
        attributes(
                'Implementation-Title': project.name,
                'Implementation-Version': project.version
        )
    }
}